variables:
  # Set `CCACHE_BASEDIR` and `CCACHE_DIR` to point `ccache` towards the cached
  # path on the gitlab-runner. This enables to cache the output of `ccache`
  # between various runs.
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  # Set `ccache` to `content` to prevent rebuilding of the CI/CD containers to
  # trigger a recreate of the cache. By using `content` the compiler's `mtime`
  # is not considered as part of the hash.
  CCACHE_COMPILERCHECK: "content"
  # Enable caching for `apt-get`.
  APT_CACHE_DIR: "${CI_PROJECT_DIR}/apt-cache"
  # Export `noninteractive` frontend to prevent requesting user input.
  DEBIAN_FRONTEND: "noninteractive"

# Define pipeline trigger behaviour. The pipeline is triggered by:
# - a merge request: run a merge request pipeline
# - a change to a branch, but an open merge reqeust: no branch pipeline
# - a change to a branch, but no open merge request: run branch pipeline
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

# Tests are separated into stages `test` and `validation`, where the latter
# should only consider explitit validation tests as defined in the
# `Validation.*` test suite.
stages:
  - build
  - test
  - validation

# Template for setting up HemoCell for each job:
# - initialising cache directories;
# - installing dependencies in the container;
# - defining the shared cache, most predominantly for `ccache`.
.job-template: &job-template
  before_script:
    # setup the environment and dependencies
    - mkdir -pv $APT_CACHE_DIR ccache
    - apt-get update --yes -qq
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install --yes -qq git g++ gcc cmake make libopenmpi-dev libhdf5-mpi-dev libhdf5-dev patch wget ccache
    # setup hemocell, e.g. patch `palabos`
    - ./setup.sh > /dev/null
    # ensure compiler commands use `ccache`
    - mkdir -p build && cd build
    - cmake .. -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
  cache:
    # Cache is shared between branches, but has a unique cache per job.
    key: "$CI_JOB_NAME"
    paths:
      # Note: directories should align with `$APT_CACHE_DIR` and `$CCACHE_DIR`.
      - apt-cache/
      - ccache/

.build-template: &build-template
  stage: build
  script:
    - cmake --build .
    - ccache --show-stats

# Excludes validation tests
.test-template: &test-template
  stage: test
  script:
    - cmake --build . --target hemocell_test
    - ccache --show-stats
    - GTEST_FILTER="-Validation.*" ctest --output-on-failure

# Only validation tests
.validation-template: &validation-template
  stage: validation
  script:
    - cmake --build . --target hemocell_test
    - ccache --show-stats
    - GTEST_FILTER="Validation.*" ctest -V

Ubuntu-build:
  image: ubuntu:20.04
  <<: *job-template
  <<: *build-template

Ubuntu-test:
  image: ubuntu:20.04
  needs: [Ubuntu-build]
  <<: *job-template
  <<: *test-template

Debian-build:
  image: debian:9
  <<: *job-template
  <<: *build-template

Debian-test:
  image: debian:9
  needs: [Debian-build]
  <<: *job-template
  <<: *test-template

Debian-validate:
  needs: [Debian-test, Ubuntu-test]
  image: debian:9
  <<: *job-template
  <<: *validation-template
