image: ubuntu:16.04

stages:
  - build
  - test

cache:
  paths:
    - cases/*/*

before_script:
  - apt-get update > /dev/null
  - apt-get -y install bc make cmake g++-5 g++ libopenmpi-dev libhdf5-dev patch python-h5py > /dev/null
  - cd ${CI_PROJECT_DIR}
  - ./setup.sh > /dev/null

build_cases:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/cases
    - make -j4 all > /dev/null

test_pipeflow:
  stage: test
  script:
    - ${CI_PROJECT_DIR}/scripts/ci/pipeflow_sanity.sh
